https://twitter.com/CutTheKnotMath/status/965995693470027776  
https://twitter.com/nntaleb/status/966797278806708224  

<img src="img/rolling_all_six.jpg"></img>

In [2]:
import numpy as np
from numpy import linalg

In [3]:
trans_mtx = np.array(
    [
        [1 / 6, 5 / 6, 0, 0, 0, 0],
        [0, 2 / 6, 4 / 6, 0, 0, 0],
        [0, 0, 3 / 6, 3 / 6, 0, 0],
        [0, 0, 0, 4 / 6, 2 / 6, 0],
        [0, 0, 0, 0, 5 / 6, 1 / 6],
        [1, 0, 0, 0, 0, 0],
    ]
)
print(trans_mtx)

[[0.16666667 0.83333333 0.         0.         0.         0.        ]
 [0.         0.33333333 0.66666667 0.         0.         0.        ]
 [0.         0.         0.5        0.5        0.         0.        ]
 [0.         0.         0.         0.66666667 0.33333333 0.        ]
 [0.         0.         0.         0.         0.83333333 0.16666667]
 [1.         0.         0.         0.         0.         0.        ]]


In [4]:
steady_state_probs = linalg.matrix_power(trans_mtx, 10000)
print(steady_state_probs)

[[0.08163265 0.10204082 0.13605442 0.20408163 0.40816327 0.06802721]
 [0.08163265 0.10204082 0.13605442 0.20408163 0.40816327 0.06802721]
 [0.08163265 0.10204082 0.13605442 0.20408163 0.40816327 0.06802721]
 [0.08163265 0.10204082 0.13605442 0.20408163 0.40816327 0.06802721]
 [0.08163265 0.10204082 0.13605442 0.20408163 0.40816327 0.06802721]
 [0.08163265 0.10204082 0.13605442 0.20408163 0.40816327 0.06802721]]


In [6]:
1 / steady_state_probs[0][-1]

14.699999999998559