https://twitter.com/CutTheKnotMath/status/1004485090892746754  
https://twitter.com/nntaleb/status/1005142681318821890  

<img src="img/street_walk.jpg"></img>

In [1]:
import pprint

import numpy as np
from numpy import linalg

Number the nodes as:  
1 2 3 4  
5 6 7 8  
9 10 11 12  
13 14 15 16  
17 18 19 20  

We are interested in probability of node 16

In [2]:
trans_mtx = np.zeros((20, 20))

# pos 1
trans_mtx[0][2 - 1] = 0.5
trans_mtx[0][5 - 1] = 0.5

# pos 2
trans_mtx[1][3 - 1] = 0.5
trans_mtx[1][6 - 1] = 0.5

# pos 3
trans_mtx[2][4 - 1] = 0.5
trans_mtx[2][7 - 1] = 0.5

# pos 4
trans_mtx[3][8 - 1] = 1

# pos 5
trans_mtx[4][6 - 1] = 0.5
trans_mtx[4][9 - 1] = 0.5

# pos 6
trans_mtx[5][7 - 1] = 0.5
trans_mtx[5][10 - 1] = 0.5

# pos 7
trans_mtx[6][8 - 1] = 0.5
trans_mtx[6][11 - 1] = 0.5

# pos 8
trans_mtx[7][12 - 1] = 1

# pos 9
trans_mtx[8][10 - 1] = 0.5
trans_mtx[8][13 - 1] = 0.5

# pos 10
trans_mtx[9][11 - 1] = 0.5
trans_mtx[9][14 - 1] = 0.5

# pos 11
trans_mtx[10][12 - 1] = 0.5
trans_mtx[10][15 - 1] = 0.5

# pos 12
trans_mtx[11][16 - 1] = 1

# pos 13
trans_mtx[12][14 - 1] = 0.5
trans_mtx[12][17 - 1] = 0.5

# pos 14
trans_mtx[13][15 - 1] = 0.5
trans_mtx[13][18 - 1] = 0.5

# pos 15
trans_mtx[14][16 - 1] = 0.5
trans_mtx[14][19 - 1] = 0.5

# pos 16
trans_mtx[15][20 - 1] = 1

# pos 17
trans_mtx[16][18 - 1] = 1

# pos 18
trans_mtx[17][19 - 1] = 1

# pos 19
trans_mtx[18][20 - 1] = 1

# pos 20
trans_mtx[15][15] = 1  # ending state we care about

In [3]:
for i in trans_mtx:
    print(i)

[0.  0.5 0.  0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0. ]
[0.  0.  0.5 0.  0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0. ]
[0.  0.  0.  0.5 0.  0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0. ]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.  0.  0.  0.  0.  0.5 0.  0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0. ]
[0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.
 0.  0. ]
[0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.5 0.  0.  0.  0.  0.  0.  0.
 0.  0. ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.5 0.  0.  0.  0.  0.
 0.  0. ]
[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.5 0.  0.  0.  0.
 0.  0. ]
[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.5 0.  0.  0.
 0.  0. ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.5 0.
 0. 

In [4]:
steady_state_probs = linalg.matrix_power(trans_mtx, 10000)
print(steady_state_probs[0])

[0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.65625 0.      0.
 0.      0.65625]


In [5]:
steady_state_probs[0, 15]  # This is C

0.65625

In [6]:
21 / 32

0.65625