https://twitter.com/CutTheKnotMath/status/1008327243280670720  
https://twitter.com/nntaleb/status/1008670089258979329  

<img src="img/ht_hh.png"></img>

In [2]:
import numpy as np
from numpy import linalg

In [3]:
trans_mtx_ht = np.array([[1 / 2, 1 / 2, 0], [0, 1 / 2, 1 / 2], [1 / 2, 1 / 2, 0]])
print(trans_mtx_ht)

[[0.5 0.5 0. ]
 [0.  0.5 0.5]
 [0.5 0.5 0. ]]


In [4]:
steady_state_probs = linalg.matrix_power(trans_mtx_ht, 10000)
print(steady_state_probs[0])

[0.25 0.5  0.25]


In [5]:
1 / steady_state_probs[0, 2]

4.0

In [6]:
trans_mtx_hh = np.array([[1 / 2, 1 / 2, 0], [1/2, 0, 1 / 2], [1 / 2, 1 / 2, 0]])
print(trans_mtx_hh)

[[0.5 0.5 0. ]
 [0.5 0.  0.5]
 [0.5 0.5 0. ]]


In [7]:
steady_state_probs = linalg.matrix_power(trans_mtx_hh, 10000)
print(steady_state_probs[0])

[0.5        0.33333333 0.16666667]


In [8]:
1 / steady_state_probs[0, 2]

6.000000000000036